### ISSUE TITLE
Tutoriel d'arrivée nouvelle BAL

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses#123]
Mettre en place un tutoriel faisant la démonstration des fonctionnalités principales de l'outil.
Apprendre où se trouvent les boutons principaux.

**Comment by tmerlier** [comment]
Une série de vidéos tutorielles est en cours de préparation.

**Comment by tmerlier** [comment]
La première série de vidéos tutorielles est prête. L’hébergement de ces vidéos ce fait actuellement sur un PeerTube privé en attendant un serveur adéquat. 

@GllmR Nous pourrions d'or et déjà préparer l'intégration de la vidéo d'introduction dans la popup d'accueil des nouveaux utilisateurs. Il nous suffira de merger quand le PeerTube sera opérationnel.
