### ISSUE TITLE
Voies à numérotation métrique

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses#127]
La numérotation métrique est de plus en plus utilisée pour adresser les communes rurales peu denses.

L'outil permet déjà de créer les numéros mais nécessite de déterminer le numéro en question par ses propres moyens (mesure au sol ou via un outil tiers).

L'objectif est de permettre une suggestion du numéro en fonction de sa position sur la voie.

Il faut donc permettre de créer des voies à numérotation métrique guidée, et donc :
- permettre le tracé linéaire de la voie dans l'outil
- permettre le choix du point de départ
- suggérer lu numéro à la création de celui-ci (mais ne jamais l'imposer)
- alerter si le numéro finalement retenu est trop éloigné de la suggestion initiale

NB : Il n'y a pas de volonté de capturer un tracé précis de la voirie

**Comment by gendy54** [comment]
J'imagine qu'on est pas à 2 m près, si?

**Comment by jdesboeufs** [comment]
Les maires aiment bien faire les choses correctement.

**Comment by tmerlier** [comment]
Corrigé par #204
