### ISSUE TITLE
Découpler les modifications de la publication

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses#136]
Lorsque une BAL est "publiée", elle est actuellement synchronisée chaque lundi avec la Base Adresse Nationale.
Ce fonctionnement automatique est jugé inadapté.

L'utilisateur devrait choisir explicitement de publier les changements.

**Comment by tmerlier** [comment]
Avec l'intégration de l'API de dépôt, il a été choisi de garder la publication automatique des mises à jour dans BAN. Cependant, les mises à jour d'une BAL peuvent être suspendues afin de ne pas remonter, temporairement, les informations dans la BAN.
