### ISSUE TITLE
Affectation du code FANTOIR

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses#140]
Aujourd'hui l'outil n'affecte pas de code FANTOIR au niveau de la BAL, ce qui génère des avertissements côté validateur.
Le code FANTOIR final est affecté au niveau de la consolidation BAN.

**Comment by GllmR** [comment]
À quel moment serait-il le plus pertinent d’ajouter le code FANTOIR ? 
À la création de la BAL ou à un autre moment ?

**Comment by fufeck** [comment]
Doublons avec la https://github.com/BaseAdresseNationale/mes-adresses-api/issues/20
