### ISSUE TITLE
Permettre l'impression papier d'une Base Adresse Locale

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#243]
L'outil ne proposant pas encore de version mobile, la possibilité de disposer d'une carte papier afin d'effectuer des repérages directement sur le terrain ou tout simplement permettre aux utilisateurs d'échanger tout ensemble autour d'une table serait un véritable atout pour les communes.

**Comment by NICEYSuzanne** [comment]
Je confirme la demande des communes, en particulier des petites, de disposer d'une carte papier.

**Comment by C-Sophie** [comment]
Une nouvelle demande déposée, la commune souhaiterait imprimer et remplacer le plan de sa commune.

**Comment by rstadel** [comment]
Complément basé sur l'utilisation sur le terrain : deux types d'impressions ("vues") sont intéressants en particuliers:
- Une voie complète, avec les numéros.
- Une vue resserrée sur une adresses particulière avec les parcelles limitrophes et un détail des positions pour les numéros imprimés.
Une option à cocher permettant l'impression de la délimitation des parcelles cadastrales serait également intéressante.
L'affichage ou non des positions d'un même numéro s'il y en a plusieurs peut également être une option à cocher.

**Comment by C-Sophie** [comment]
La demande est renouvelée : la DGFiP demande aux communes un plan des voies.
