### ISSUE TITLE
Erreur 500 en accédant à une BAL contenant une commune périmée

### ISSUE THREAD

**Issue by cedric-famibelle-pronzola** [BaseAdresseNationale/mes-adresses#268]
Exemple :

nom : Base Adresse Locale de Haute-Savoie
id : 5e26d8d9b6a9357fd9ebf2e2

contient deux communes périmées : 
- 74110
- 74274

*lien* 
https://mes-adresses.data.gouv.fr/bal/5e26d8d9b6a9357fd9ebf2e2

*capture*
![Capture BAL](https://user-images.githubusercontent.com/45098730/100475984-bc9cc700-30e4-11eb-8888-2974ad52cfaa.PNG)

**Comment by tmerlier** [comment]
Corrigé par #431
