### ISSUE TITLE
différenciation des routes communales, d'accès et chemins sur la carte

### ISSUE THREAD

**Issue by juliencarnot** [BaseAdresseNationale/mes-adresses#282]
Le fond de carte utilisé utilise la même représentation pour des routes de types très différents:
https://wiki.openstreetmap.org/wiki/FR:Tag:highway=track -> chemin plus ou moins carrossable
https://wiki.openstreetmap.org/wiki/FR:Tag:highway=service -> voies d'accès
https://wiki.openstreetmap.org/wiki/FR:Tag:highway=unclassified -> voies communales

Pour plus de lisibilité, il serait utile de donner moins de poids aux chemins et voies d'accès, par exemple comme sur le rendu OSM-FR:
![image](https://user-images.githubusercontent.com/3848493/102604613-b66a9b00-4124-11eb-82dc-c31cd44ead4c.png)

pour comparaison la carte mes-adresses:
![image](https://user-images.githubusercontent.com/3848493/102604702-def29500-4124-11eb-8601-dddb040d128d.png)

**Comment by tmerlier** [comment]
La distinction des différents type de voie est désormais possible grâce à l'ajout du fond "Plan IGN" #463.
Ce plan est encore en bêta, tous les retours sont les bienvenus :)
