### ISSUE TITLE
Un vrai export Excel et éventuellement préciser l’encodage de sortie pour le CSV

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/mes-adresses#355]
L'export csv qui s'ouvre dans excel avec un encodage UTF8 qui du coup n'est pas très compatible (des caractères spéciaux s'affichent) et peut en effrayer plus d'un.
Il serait intéressant d'avoir un vrai export Excel et éventuellement préciser l’encodage de sortie pour le CSV.

**Comment by juliencarnot** [comment]
Hum, peut-être vouliez-vous dire ODF (Open Document Format for Office Applications), le format recommandé par le RGI (et qui s'ouvre dans les suites propriétaires Microsoft) , cf. https://www.numerique.gouv.fr/uploads/Referentiel_General_Interoperabilite_V2.pdf ? ;-)

**Comment by tmerlier** [comment]
Les fichiers doivent être manipulés par des utilisateurs "experts" ou au moins qui savent les manipuler. Si des utilisateurs "amateurs" sont amenés à les ouvrir, c'est que le problème est ailleurs.
