### ISSUE TITLE
Problème d'affichage des boutons du `header` sur un écran réduit

### ISSUE THREAD

**Issue by GllmR** [BaseAdresseNationale/mes-adresses#366]
Lorsque la taille du navigateur est réduite, les boutons du sous-`header` se chevauchent et un des boutons sort du `header`.

![image](https://user-images.githubusercontent.com/56537238/124619204-bdff5080-de78-11eb-9c44-5b39b8f0d158.png)

**Comment by fufeck** [comment]
![Capture d’écran 2023-04-12 à 16 11 49](https://user-images.githubusercontent.com/8143924/231453287-1d6d0320-4dee-4fa9-bd40-ca8e0980341d.png)

Je ne retrouve pas le bug, il a du être corriger.
Peut on clore l'issue?
