### ISSUE TITLE
Redirection automatique sans page 404 lorsqu'une BAL n'est pas trouvée (ancien nom de domaine)

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#384]
## Contexte
Lorsqu'une BAL n'existe plus car supprimée par exemple, l'utilisateur est directement redirigé vers la page d'accueil sans aucune explication.

Cela pose problème car si une commune tente d'accéder à une BAL via un mail et retombe directement sur la page d'accueil sans plus d'explication, elle risque de ne pas comprendre que la BAL n'existe plus.

Tester le comportement : https://editeur.adresse.data.gouv.fr/bal/5dc1bbe8cb4f454258bc8b22

## Solution
Afficher une page 404 affichant comme message que la BAL demandée n'a pas été trouvé car incorrect ou supprimée.

Il pourrait aussi être intéressant d'avoir en page d'accueil la liste des BAL introuvables afin d'informer que la BAL n'est plus disponible et proposer une suppression du token.

**Comment by tmerlier** [comment]
La redirection vers la page d'accueil ne se produit pas parce que la BAL n'est pas trouvée mais parce que le lien pointe vers l'ancien nom de domaine `editeur.adresse.data.gouv.fr`. La redirection vers `mes-adresses.data.gouv.fr` est toujours effective mais la migration des `id` et `tokens` de l'utilisateur ne le sont plus car depuis l'incident OVH, toutes ces BAL ont étaient perdues.

Néanmoins, il reste à trouver une solution pour informer l'utilisateur que sa BAL n'est plus disponible. 
Solutions possible:
1. Une simple erreur `404` (intervenir sur la redirection du nom de domaine)
2. Informer par mails les communes concernées (retrouver les communes)
3. Recrée automatique une BAL avec les données disponible

Les solutions 2 et 3 peuvent être complémentaire.

**Comment by tmerlier** [comment]
Ajout du tag "question" afin de savoir si c'est toujours un problème connu du support et soumettre son abandon dans le cas contraire.

**Comment by GllmR** [comment]
Cette Issue n’est plus d’actualité, le problème est ancien et ne concerne que les BALs n’ayant pas été mises à jour depuis plus d’un an.

**Comment by tmerlier** [comment]
Le problème est toujours d'actulité, il concerne les personnes ayant créer une BAL avant le changement de nom de domaine et n'ayant pas modifié leur BAL depuis. 

Mais à ce jour, aucune demande n'est remontée dans le support concernant ce problème.
