### ISSUE TITLE
Le découpage administratif n'est pas affiché sur le plan orthophoto

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#464]
### Contexte
Le découpage administratif bien que présent dans le fichier `ortho.json` n'est pas visible sur le fond orthophoto.

### Description
Aucun style n'est fourni que ce soit pour la couche `regions`, `departements` ou `commune`, de ce fait la carte n'affiche rien. Cette anomalie est passée inaperçu car le fond vectoriel OSM dispose déjà d'une couche pour le découpage administratif.

### À faire
- [x] Ajouter un style pour le découpage administratif (prendre exemple sur le cadastre)
- [x] Filtrer le découpage administratif déjà présent sur le fond OSM

Ce style pourra être chargé directement dans le hook dédier aux layers. Nous pourrions ainsi changer dynamiquement le style en fonction du fond de carte utilisé.

Ou alors définir un style "en dur" directement dans les fichiers json qui soit déjà adapté au fond en question.

**Comment by vinsag** [comment]
@tmerlier : La partie decoupage-administratif est bien présent dans ortho.json, l'url a changé ? A moins que nous parlons d'autre chose

**Comment by tmerlier** [comment]
> @tmerlier : La partie decoupage-administratif est bien présent dans ortho.json, l'url a changé ? A moins que nous parlons d'autre chose

Comme précisé dans la description au-dessus, c'est le style de la couche qui est absent. La donnée est bien présente.

**Comment by tmerlier** [comment]
Corrigé par #558
