### ISSUE TITLE
Améliorer l'action de certification de toutes les adresses de la commune

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#465]
### Contexte
Le bouton permettant de certifier tous les adresses d'une BAL se trouve juste en dessous de la gestion des utilisateurs. Il est arrivé que des utilisateurs confondent le terme "adresse mail" et "adresse BAL" et ont certifiés toutes les adresses de la commune pensant valider les adresses emails des administrateurs de la BAL.

### Solution
Séparer plus clairement les deux actions afin qu'aucune confusion ne soit possible.

**Comment by tmerlier** [comment]
Cette action pourrait être accessible sur la page /bal #507

**Comment by MaGOs92** [comment]
Ce bouton a été déplacé et se trouve maintenant dans l'onglet commune dans la section "Certification".
