### ISSUE TITLE
Préciser les dates de mise à jour des fonds de carte et du cadastre

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/mes-adresses#467]
Préciser la date de mise à jour des fonds de carte et le millésime du cadastre. 

Source : demande des partenaires de la Charte le 2/12.

**Comment by vinsag** [comment]
Pour les plans fond de carte "Plan IGN" et Photographie aérienne"(Orthophotos) les copyright IGN renvoient vers les informations sur les fonds de carte ou apparait une date de mise à jour.

Il faut maintenant traiter le cas des fonds de carte Etalab Cadastre

**Comment by Maxine-Le-Pennec** [comment]
> Préciser la date de mise à jour des fonds de carte et le millésime du cadastre.
> 
> Source : demande des partenaires de la Charte le 2/12.

### **UPDATE**
Le fond de carte ETALAB comprend à présent dans ses attributions, la date de mise à jour du cadastre ainsi qu'un lien redirigeant vers [cadastre.gouv](https://cadastre.data.gouv.fr/)
