### ISSUE TITLE
Le champ "suffixe" enregistre les saisies en majuscule

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#469]
## Description
Le champ "suffixe" permet actuellement de saisir des lettres majuscules bien qu'il affiche la saisi en minuscule.

### Saisie
![image](https://user-images.githubusercontent.com/7040549/146570428-de6edec1-a325-408c-8e99-d56b14a5ff32.png)
### Résultat
![image (1)](https://user-images.githubusercontent.com/7040549/146570441-06db46d4-6731-4532-856f-cf1226f7e11f.png)

## Solution
Modifier directement la saisie dans le champ "suffixe" afin de forcer son les lettres minuscule.

**Comment by bienf007** [comment]
En fait la saisie s'affiche en minuscule dans tous les cas. Le résultat est lui correct. Juste un bug d'affichage dans le champs de saisies.
Dan le css inline de ce champ  `<input  type="text" placeholder="Suffixe" spellcheck="true" aria-invalid="false" maxlength="10" value="" style="text-transform: `lowercase;">`  Il faudrait supprimer le style `style="text-transform: lowercase;".`
