### ISSUE TITLE
Suppression soft d'une BAL

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses#482]
Actuellement la suppression d'une BAL est une suppression totale et définitive.
Il serait plus prudent de mettre en place une suppression "soft" avec une période de grâce.

Le même comportement pourrait être imaginé pour les voies et les numéros à l'avenir.

**Comment by tmerlier** [comment]
Quelques éclaircissements sont nécessaires avant de lancer ce chantier :
- Le nouveau champ permettant d'identifier une BAL supprimée pour être : 
   - `_deleted` afin qu'il soit géré grâce protégé et puisse être géré par `mongo.decorateCreation` comme `_updated` et `_created`. Il sera donc nécessaire de prévoir une route dédiée à la restauration d'une BAL (ex : `/bases-locales/{id}/restore`
   - `deletedAt` afin de pouvoir être modifié directement avec `updateSchema`
- Combien de temps pourrait être jugé comme raisonnable ? 1 mois ?
- Est-ce l'API ou le front qui s'occupe de filtrer les BAL supprimée dans le dashboard ?

TO DO
- [ ] Ajouter le champ `_deleted` ou `delatedAt` contenant la date de suppression
- [ ] Créer la route `/bases-locales/{id}/restore` si le champ est protégé
- [ ] Écrire un script de migration qui ajoute ce champ aux bases locales existantes
- [ ] Écrire un cron job afin de supprimer définitivement les BAL après `1 mois`
