### ISSUE TITLE
Remplacer MapboxGL par MapLibre

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#496]
## Résumé
Remplacer `mapbox-gl` par `maplibre-gl` qui est sa reprise open source.

## Contexte
La bibliothèque `react-map-gl` utilise actuellement `mapbox-gl` qui aujourd'hui n'est plus sous licence ouverte. Mais son projet a été repris en licence ouverte sous le nom de `maplibre-gl`. Cependant, cette reprise open source a été faite sous une version antérieur à celle que nous utilisons.

## Pré-requis
- [x] S'assurer que les fonctionnalités de `mapbox-gl` que nous utilisons sont aussi disponible sur `maplibre-gl`
- [x] S'assurer que `react-map-gl-draw` fonctionne sous `maplibre`

**Comment by vinsag** [comment]
J'ai vu exemple dans la documentation maplibre avec l'utilisation react_map_gl_draw mais il faudrait tester : https://maplibre.org/maplibre-gl-js-docs/example/mapbox-gl-draw/
Je n'arrive pas à trouver un comparatif complet entre les 2 fonctions. Je ne trouve pas certaines fonctionnalités.
Je pense qu'il faudrait tester les scripts en faisant le remplacement

**Comment by vinsag** [comment]
Après avoir repris le sujet, une question se pose nous pouvons utliser le react-map_gl draw en contournant le jeton mapbox mais nous resterons dans une version inférieur et nous ne pourrons pas trop faire évoluer le module. Pour l'instant il n'y a rien d'urgent sur ce ticket si nous restons en dessous de la version . On peut envisager de faire une évolution vers Open Layer qui a des modules react aussi.
