### ISSUE TITLE
Bug d'affichage liste des administrateurs

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses#500]
Sous Safari, la liste des administrateurs dépasse du panneau qui la contient.

<img width="312" alt="Capture d’écran 2022-02-24 à 16 47 32" src="https://user-images.githubusercontent.com/1231232/155558363-3c074305-0e42-4d75-964b-e70709283a54.png">

**Comment by GllmR** [comment]
Fixed by #504
