### ISSUE TITLE
Absence d'espacement dans le listing des BAL

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses#501]
Il manque un espace entre le tiret `-` et le nom de la commune concernée par la BAL.

![Capture d’écran 2022-02-24 à 16 51 17](https://user-images.githubusercontent.com/1231232/155558940-19d4644a-e698-4f33-a78e-53d061af1959.png)

**Comment by tmerlier** [comment]
Corrigé par #510
