### ISSUE TITLE
Bandeau "Essayez l'outil" écrasé

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses#502]
Sous Safari, le bandeau qui invite à essayer l'outil est écrasé, et de fait relativement invisible.
Cette fonctionnalité devrait être davantage mise en avant.

<img width="733" alt="Capture d’écran 2022-02-25 à 12 09 08" src="https://user-images.githubusercontent.com/1231232/155705315-5bca4cd6-ad8d-420e-8f8d-16df3efe0a32.png">

**Comment by vinsag** [comment]
Suite au commentaire de Maxine sur le ticket nous pouvons le fermer ou est il toujours d'actualité ?
