### ISSUE TITLE
BAL en conflit avec elle même

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#508]
## Contexte
Il a été remonté par le support qu'une BAL était en conflit alors que celle-ci n'a pas de "concurrence". La capture d'écran confirme que la BAL est en conflit avec elle même.

### Informations
- BAL de la commune de La Roche en Brenil (21525)
- Problème constaté après la publication du 01/03/2022 à 13h44
- Lien vers la BAL: https://mes-adresses.data.gouv.fr/bal/60f92e5abad34c3df59be826

![Capture d’écran 2022-03-03 à 15 26 47](https://user-images.githubusercontent.com/7040549/156586652-c7a816fc-1c74-45e3-bbf6-1f2c13404662.png)

**Comment by C-Sophie** [comment]
Vu aujourd'hui aussi avec Faramans 

Idéalement, ajouter dans le cadre conflit de cliquer sur "Base Adresse Nationale" pour forcer la publication  

<img width="518" alt="Capture d’écran 2022-03-07 à 13 54 13" src="https://user-images.githubusercontent.com/69309231/157038432-b78c26b9-e76a-4240-b374-ca57d69f7796.png">

**Comment by C-Sophie** [comment]
Pignans. 
Lorsqu'on clique sur Base Adresse Nationale, l'écran "buggue" (pas le temps de faire une capture d'écran) > une erreur est survenue > et retour à la liste des BAL. 

![Pignans](https://user-images.githubusercontent.com/69309231/157049431-51f2b561-301f-42b8-bae2-2bdcbda703e0.gif)

**Comment by jdesboeufs** [comment]
On va regarder.
Si possible ne pas résoudre le conflit à ce stade.

**Comment by tmerlier** [comment]
> Pignans. Lorsqu'on clique sur Base Adresse Nationale, l'écran "buggue" (pas le temps de faire une capture d'écran) > une erreur est survenue > et retour à la liste des BAL.
> 
> ![Pignans](https://user-images.githubusercontent.com/69309231/157049431-51f2b561-301f-42b8-bae2-2bdcbda703e0.gif)

Cette erreur est provoquée car les `context.extras` de la `revision` est `null` et ne dispose donc pas de la `balId` attendu. Cela vient du fait que la BAL a été crée via le Guichet Adresse et non Mes Adresses. je crée une issue concernant ce problème.

**Comment by tmerlier** [comment]
Remplacé par BaseAdresseNationale/mes-adresses-api/issues/318

**Comment by tmerlier** [comment]
Un nouveau cas vient d'être remonté par le support.

La commune de Arzon n'a qu'une seule BAL mais celle-ci est pourtant en conflit :
https://mes-adresses.data.gouv.fr/bal/608fcb0781a8756eeb943762

Révisions: https://plateforme.adresse.data.gouv.fr/api-depot/communes/56005/revisions

**Comment by j-saur** [comment]
Un nouveau cas vient d'être remonté par le support.

La commune de Aveize n'a qu'une seule BAL mais celle-ci est pourtant en conflit :
https://mes-adresses.data.gouv.fr/bal/615324b3c1f68215be73aa36

Révisions: https://plateforme.adresse.data.gouv.fr/api-depot/communes/80360/revisions

**Comment by tmerlier** [comment]
Je pense avoir enfin pu mettre le doigt sur le problème. 

Si la publication d’une révision échoue, celle-ci est tout de même sauvegarder comme la dernière révision pour la BAL. Par conséquent, la révision courante de l'API de dépôt devient donc différente de celle de la BAL.

**Comment by j-saur** [comment]
Un nouveau cas vient d'être remonté par le support.

La commune de PLAGNOLE n'a qu'une seule BAL mais celle-ci est pourtant en conflit :
https://mes-adresses.data.gouv.fr/bal/6214d82a9637f415b02d43b9

Révisions: https://plateforme.adresse.data.gouv.fr/api-depot/communes/31423/revisions

**Comment by tmerlier** [comment]
Pour toutes les révisions avant le 28/03, il faut simplement dire à la commune de forcer la publication. Un correctif a été mis en place, il faudra voir si ce genre de conflit se reproduit.

Il n'est pas utile de lister les BAL en conflit.

**Comment by fufeck** [comment]
@j-saur @MaGOs92, avons nous eu un conflit de bal depuis le patch ?

**Comment by fufeck** [comment]
Doublons avec la https://github.com/BaseAdresseNationale/mes-adresses-api/issues/318
