### ISSUE TITLE
Afficher l'adresse au survol des numéros

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/mes-adresses#515]
Demande d'un utilisateur : est-il possible d'afficher les n° dans "Mes Adresses" en pointant la souris au survol comme dans l'explorateur de la Base Adresse Nationale. Objectif : gain de temps qui éviterait d'ouvrir toute la voie pour vérifier l'emplacement où l'on se trouve, puis de revenir à la liste de toutes les voies.

Référence : ticket sur le support 4610431

**Comment by tmerlier** [comment]
Nécessite que #520 soit terminé.
