### ISSUE TITLE
Erreur de propType dans la partie "Besoin d’aide ?" 

### ISSUE THREAD

**Issue by GllmR** [BaseAdresseNationale/mes-adresses#525]
Dans la partie "Besoin d’aide ?" du site, une erreur de propType est affichée lorsque l'on clique sur l’onglet "Publication".

Erreur : 
```javascript
Warning: Failed prop type: Invalid prop `sync.status` of value `conflit` supplied to `StatusBadge`, expected one of ["synced","outdated","conflict"].
```

**Comment by vinsag** [comment]
Comme la branche a été mergée le 17 mai, je ferme le ticket
