### ISSUE TITLE
Préférences utilisateurs

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#530]
## Contexte
Il est actuellement impossible de configurer l'interface de l'outil aux besoins/avis d'un utilisateur, seuls les paramètres de la BAL peuvent être modifiés et impacterons donc tous les administrateurs.

Avec la création d'un contexte utilisateur dédié qui serait sauvegardé dans le `local-storage` il serait possible d'envisager des fonctionnalités comme le mode daltonien #499.

**Comment by MaGOs92** [comment]
Done!
