### ISSUE TITLE
creer un signalement contenant les nouveaux tracé de voie d'une BAL

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/mes-adresses#533]
Lorsqu'une BAL est publiée dans la BAN, voir pour envoyer un signalement / des signalements en cas de tracé d'une nouvelle voie métrique. Utiliser l'API de signalement https://espacecollaboratif.ign.fr/gcms/api/doc/
POST /gcms/api/reports 
A décrire plus précisément les champs à remplir et comment.

**Comment by tmerlier** [comment]
La fonctionnalité de tracé de voie n'a pas vocation à fournir un tracé exact et ne peut donc pas être utilisé pour remonter des informations de voirie.
