### ISSUE TITLE
Problème de rafraichissement des nouveaux numéros

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#553]
### Contexte
Lorsque l'on ajoute un nouveau numéro à une voie celui-ci n'est plus affiché lorsque l'on quitte la voie. Il faut rafraichir la page pour le voir apparaitre.

### Reproduire
- Créer une nouvelle voie
- Ajouter un numéro
- Cliquer sur une voie à côté

**Comment by j-saur** [comment]
https://user-images.githubusercontent.com/95912586/163409677-728174fa-96cb-4cbe-b5c8-7b6c2421af8f.mp4
