### ISSUE TITLE
Problème de surbrillance des parcelles sélectionnées

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#573]
## Contexte
Il peut arriver que l'effet de surbrillance des parcelles sélectionnées ou survolées ne fonctionne pas. Pour le moment, le problème n'a pas été identifié et n'est pas récurrent. Lorsqu'il se produit, il suffit de recharger la page pour le faire disparaitre.

**Comment by vinsag** [comment]
Je n'arrive pas à reproduire l'erreur aussi bien en mode dev en local que prod

**Comment by IGNFBourcier** [comment]
J'ai trouvé 2 scenarri où iu /carte ne reflétant pas l'état du formulaire.

scenarii 1
commencer au niveau liste des voies d'une commune.
- activer le cadastre
- consulter une voie
- modifier /editer un numero
- ajouter une parcelle
- enregistrer
=> on retourne sur la liste des numeros de la voie automatiquement
! la parcelle ajoutée n'est pas bleutée.


scenarii 2
commencer au niveau liste des numeros d'une voie
- activer le cadastre
- cliquer pour modifier /editer un numero (possédant au moins une parcelle sélectionnée)
=>le formulaire indique la parcelle, sur la carte la parcelle rattaché au numéro n'est pas différencié des autres parcelles rattéché à d'autre numeros de la voie.
![image](https://user-images.githubusercontent.com/62593305/176938469-67386591-2faa-448d-a1f9-8b5fb687d891.png)

Dans le secanii2 , si on active le cadastre seulement une fois sur l'édition du numéro on a bien la différentiation
![image](https://user-images.githubusercontent.com/62593305/176939426-97bd035c-1db3-428e-9279-e7e1585fc938.png)
