### ISSUE TITLE
outil mes-adresses : affichage numéro de parcelle manquant

### ISSUE THREAD

**Issue by nicolaschuz** [BaseAdresseNationale/mes-adresses#580]
Depuis peu, lorsque l’on clique sur un numéro dans l’outil mes-adresses que l’on a certifié au préalable, en ayant associé un numéro de parcelle, le numéro de parcelle n’apparait plus (mais on sait que la parcelle est bien associée, car elle reste avec un fond de couleur bleue).
Si l’on reclique sur la parcelle, on voit à nouveau le numéro, la parcelle passe en fond rouge, on peut certifier à nouveau, et hop le numéro de parcelle disparait ensuite…

**Comment by tmerlier** [comment]
Doublon avec #574. C'est en cours de correction [ici](https://github.com/BaseAdresseNationale/mes-adresses/pull/578).

Merci pour votre retour !
