### ISSUE TITLE
afficher la (non) compatibilité avec la norme AFNOR NF Z 10-011

### ISSUE THREAD

**Issue by nicolaschuz** [BaseAdresseNationale/mes-adresses#600]
Le SNA de la Poste nous alerte que certaines adresses créées dans notre BAL sont incompatibles avec la norme AFNOR NF Z 10-011.

Ce serait utile d'avoir une alerte lors de la création d'une voie ou un numéro incompatible.

Concernant le numéro : il doit comporter
> soit de 0 à 4 caractères numériques
> soit de 1 à 3 caractères numériques suivis d’un espace et d’un caractère alphabétique correspondant à
l’abréviation de BIS (B), TER (T), et QUATER (Q) ou à A, B, C, D... lorsque ces caractères complètent le numéro de rue.

**Comment by tmerlier** [comment]
Bonjour,

l'outil n'a pas pour objectif de produire des adresses compatibles avec la norme AFNOR, mais des adresses entières telles que présentes dans les délibérations des communes.
Ce n'est donc pas une fonctionnalité qui sera ajoutée à Mes Adresses.

Je vous remercie pour votre compréhension et de votre retour.
