### ISSUE TITLE
Griser l'option "initialiser à partir de la BAN" quand il n'y a pas de données

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses#605]
Actuellement on permet de cocher la case "Initialiser à partir de la BAN" même quand il n'y a pas de données.
Ça fonctionne, mais ça produit bien sûr une BAL vide.

Il serait plus légitime d'afficher une alerte ou de grise l'option.

**Comment by j-saur** [comment]
Non considéré car :
- L'ajout d'appel à l'API dépot + l'API BAN supplémentaire 
- L'arrivée au même résultat (une BAL vide)
- Le peu de communes concernées
