### ISSUE TITLE
Pré-remplir le nom de la BAL ou rendre le champ optionnel

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses#608]
Maintenant qu'une BAL est nécessairement communale (plus de BAL multi-communale) il serait pertinent de pré-remplir le nom de la BAL à partir de la commune sélectionnée.

Cela signifierait changer l'ordre des champs dans le formulaire de création :)

**Comment by VeitchM** [comment]
I will try to have it done for this Monday

**Comment by VeitchM** [comment]
I did a PR
