### ISSUE TITLE
Les toponymes avec parcelle(s) associée(s) ne remontent pas dans la BAN

### ISSUE THREAD

**Issue by j-saur** [BaseAdresseNationale/mes-adresses#622]
### Les toponymes avec parcelle(s) associée(s) ne remontent pas dans la BAN

Comportement attendu : 
- Publication d'une BAL avec ses toponymes
- Tous les toponymes remontent dans la BAN

Comportement observé : 
- Publication d'une BAL avec ses toponymes
- Seul les toponymes sans parcelles associées remontent dans la BAN

Exemple de Percy-en-Normandie suite à leur signalement : 
Liste des toponymes dans la BAN : 
https://adresse.data.gouv.fr/base-adresse-nationale/50393#12.68/48.91751/-1.1935
![image](https://user-images.githubusercontent.com/95912586/174251775-4a3f239a-f18e-4588-be22-81a52bf968d7.png)
Liste des toponymes dans la BAL : 
https://mes-adresses.data.gouv.fr/bal/60a3ca908e3f886dc7f7dd07
![image](https://user-images.githubusercontent.com/95912586/174252204-f03dadc0-f967-4b04-bfa2-cd2268b1331f.png)

Les toponymes absents sont ceux qui ont au moins une parcelle associé, à savoir : 
  La Gouisserie
  Le Hamel ès Hervy
  Chemin de la Monnerie
  La Benoistière
  La Castellière
  La Castellière
  Le Festel

**Comment by fufeck** [comment]
Lorsque je télécharge le csv et que je créer une nouvelle bal a partir du csv, j'ai bien les lieux dits mais pas leurs parcelles associées, est ce normale ??

**Comment by j-saur** [comment]
Issue présente côté BAN
