### ISSUE TITLE
Empêcher la publication de BAL sans adresse

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/mes-adresses#627]
La commune de Manas-Bastanous - 32226 (82 habitants, sans adresse dans la BAN) a renseigné ses voies dans la liste des toponymes car elle n'a pas encore réalisé le numérotage. 
La liste des voies et des numéros est vide. 

La commune peut quand même publier, sans BAL est indiquée comme "à jour"
<img width="570" alt="Capture d’écran 2022-06-23 à 09 22 03" src="https://user-images.githubusercontent.com/69309231/175240081-0999b729-f8c0-4b53-8120-de49795046fd.png">

Or les adresses restent composite dans la BAN, sans prise en compte des voies sans adresse.
<img width="450" alt="Capture d’écran 2022-06-23 à 09 23 08" src="https://user-images.githubusercontent.com/69309231/175240270-ac24b506-355b-411e-84f6-5771b730791a.png">

**La commune se tourne vers le support :** 
La réponse à apporter est que la Base Adresse Locale n'est pas reconnue car ne comprenant aucune adresse (pas de numéro).

Prévoir une info dans l'outil ? Que préciser dans le Guide de l'éditeur ?

**Comment by tmerlier** [comment]
Corrigé par https://github.com/BaseAdresseNationale/mes-adresses-api/pull/355
