### ISSUE TITLE
Dernière parcelle inaccessible quand un grand nombre est sélectionné

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#661]
## Contexte
Lorsqu'un numéro possède un grand nombre de parcelles et que celles-ci s'affichent sur quatre colonnes, il devient impossible de cliquer sur le dernier. Lorsque la poubelle se rajoute, la parcelle passe à la ligne suivante.

**Problème constaté sur le navigateur `edge`** (version non précisée)

**Comment by GllmR** [comment]
Après installation de la dernière version de Edge (104), je n’ai pas réussi à reproduire le problème.
Testé sur écran de Macbook, écran 1080p et 4K.

Il nous faudrait plus de détails et une capture pour mieux comprendre le problème.

![Capture d’écran 2022-08-10 à 15 07 44](https://user-images.githubusercontent.com/56537238/183909698-0edc7472-2c21-444f-9d85-3f434680d010.png)

**Comment by GllmR** [comment]
@IGNFBourcier Est-ce que tu peux nous faire une capture ou nous donner plus de précision sur la manière de reproduire ce bug ?

**Comment by IGNFBourcier** [comment]
Sur windows 10 edge (103 puis 104) j'ai la liste des parcelles sur 4 colonnes. Si je vais sur un element de la quatrieme colonne il passe à la ligne suivante (en 1ere colonne) en devanant rouge avec l'icone 🗑️ et revient à sa place en vert sans icone. Le pointeur souris lui aussi clignote entre ✋ (main) et 👆 (pointeur). 
![Image collée à 2022-8-9 11-30 (1)](https://user-images.githubusercontent.com/62593305/185935653-e163d038-1c73-49f1-90d2-a489aab70a63.png)
![Image collée à 2022-8-9 11-30](https://user-images.githubusercontent.com/62593305/185935668-163a81b7-89a6-4104-a795-31904796c9a3.png)
Les elements clignotent comme celà et parfois ca se stabilise plus ou moins vite: Le pointeur est en quatrieme colonne mais l'élément selectionné est en 1ere colonne de la ligne du desssous.
C'est un peu déstabilisant.

**Comment by IGNFBourcier** [comment]
> Tu pourrais nous indiquer la résolution de ton écran ?
> Je n’arrive pas à avoir quatre colonnes sur les écrans à ma disposition.
ecran du portable 1920*1080
second ecran en 1280*1024 
sur les 2 j'ai les 4 colonnes

**Comment by IGNFBourcier** [comment]
Avec firefox 91 esr sur l'ecran du portable j'ai 4 colonnes, mais sur le second ecran j'en ai 3 😵.
la taille du rendu du contenu des badges semble changer.
