### ISSUE TITLE
La carte se centre sur la première position définie

### ISSUE THREAD

**Issue by GllmR** [BaseAdresseNationale/mes-adresses#665]
Lorsqu’un numéro possède plusieurs positions, la carte est centrée sur la première position, sans prendre en compte le type de position.

Il faudrait que la carte soit centrée sur l'ensemble des numéros.

Reproduction : 

- Créer une voie
- Ajouter un numéro avec deux positions éloignées, la première position ne doit pas être de type "entrée"
⇾ On constate que lorsqu’on sélectionne la voie, la carte est centrée sur la première position.

Captures : 

![image](https://user-images.githubusercontent.com/56537238/184322568-b5703ae4-bb11-4a6a-bc6a-06b7edaa30ed.png)

![image](https://user-images.githubusercontent.com/56537238/184322677-22738b53-78f4-4b23-a800-ba5c510cefa5.png)

![image](https://user-images.githubusercontent.com/56537238/184322760-24e275f8-2637-4403-a596-9f9262b50928.png)

**Comment by tmerlier** [comment]
Je propose que l'on fasse un `fitbound` sur toutes les positions quand il y en a.

**Comment by tmerlier** [comment]
cf #591
