### ISSUE TITLE
Modifier la gestion du zoom

### ISSUE THREAD

**Issue by I-Thibaud** [BaseAdresseNationale/mes-adresses#708]
Bonjour,

Depuis quelques temps (1mois ou 2), la gestion du zoom automatique a évolué. Désormais lorsque nous cliquons sur un point adresse, le zoom revient toujours à l'échelle de la voie.

C'est très embêtant car lorsque nous modifions une grande voie, Il faut cliquer sur le point (zoom automatique au niveau de la voie) , zoomer manuellement pour gérer l'emplacement du point en lien avec le cadastre, puis nous cliquons sur le point adresse suivant (souvent à côté) et le zoom revient au niveau de la voie, il est donc nécessaire de rezoomer. C'est très chronophage.

Par avance merci de revoir le système de zoom.

**Comment by tmerlier** [comment]
Oui effectivement, je l'ai constaté aussi. On se penche dessus ! Merci pour votre retour.
