### ISSUE TITLE
Convertir une voie sans numéro en toponyme

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#710]
## Contexte
Il arrive fréquemment que des communes créent des voies sans adresse qui, dans la grande majorité des cas, devraient être des toponymes. De plus les voies sans adresse ne remonte pas la BAN.

## Évolutions
Permettre de "convertir" une voie sans adresse en toponyme grâce à une action disponible dans le menu de la voie.
Cette opération devra être effectuée par une route dédiée sur mes-adresses-api.

https://user-images.githubusercontent.com/7040549/192749231-d33eed60-8cee-43b4-83ce-f20c45909f23.mov

## PR

- [ ] https://github.com/BaseAdresseNationale/mes-adresses-api/pull/374
- [ ] https://github.com/BaseAdresseNationale/mes-adresses/pull/751

**Comment by fufeck** [comment]
[ ] https://github.com/BaseAdresseNationale/mes-adresses-api/pull/374
[ ] Ajouter le bouton convertir dans les actions des Row des voie
