### ISSUE TITLE
Permettre l'habilitation à tout moment

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#711]
## Contexte
Il est actuellement impossible de faire une demande d'habilitation pour une BAL en dehors du processus de publication.
Or cette demande pourrait techniquement être faite à tout moment et permettrait de distinguer plus facilement les BAL tenues par des communes. Cela permettrait également de faciliter le travail d'accompagnement des partenaires.

## Évolution
Ajouter un moyen de faire la demande d'habilitation accessible depuis les paramètres ou depuis l'en-tête. Une BAL habilitée doit pouvoir se distinguer visuellement et sa durée de validité devrait être renseignée.

Une icône est pour le moment affichée en haut à gauche de l'en-tête lorsqu'une BAL est habilité, cependant cela n'a rien d'explicite et ne permet pas de connaitre la période de validité de l'habilitation.

**Comment by MaGOs92** [comment]
Cette évolution a été testé puis abandonnée lors du développement de l'onglet commune.

Le mécanisme de renouvellement d'habilitation était de créer une habilitation "orpheline" et de la rattacher la BAL courante uniquement lorsque l'authentification est réussie. Ainsi l'utilisateur ne perd pas son habilitation actuelle si l'authentification n'aboutie pas. Ce mécanisme fonctionne bien avec l'authentification via code PIN mais pose problème avec l'authentification via France connect. Nous avons choisi de ne pas l'implémenter car le jeu n'en valait pas la chandelle

**Comment by fufeck** [comment]
@MaGOs92 quand est il de cette issue du coup https://github.com/BaseAdresseNationale/mes-adresses/issues/715 ??
