### ISSUE TITLE
Erreur sur les parcelles de section E

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/mes-adresses#719]
Les parcelles situées dans des sections E se trouvent mal codées par Mes Adresses : la parcelle cadastrale apparait alors en format de cellule « Scientifique » en notation exponentielle.
Dans la BAN en sortie également. 

Exemple : Sap-en-Auge https://adresse.data.gouv.fr/commune/61460

Source : ticket "BAL Sap-en-Auge 61460", Ticket#4630380

**Comment by tmerlier** [comment]
Le problème vient de la configuration logiciel utilisé pour afficher le fichier CSV et non du fichier lui-même.
