### ISSUE TITLE
Le lien d'administration ne donne pas immédiatement accès à l'édition

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#752]
## Contexte
Lorsqu'un utilisateur clique sur le lien d'administration de sa BAL reçu par email : https://mes-adresses.data.gouv.fr/bal/{idBAL}/{token} celui est redirigé vers la BAL et le jeton est bien stocké dans son `localstorage`.
Cependant l'édition n'est toujours pas accessible, il est alors nécessaire de rafraichir la page.

## Reproduire
1. Créer une BAL
2. Supprimer le token dans le `localStorage` du navigateur
3. Rejoindre l'url https://mes-adresses.data.gouv.fr/bal/{idBAL}/{token}
4. Le label "Édition impossible" sera affiché en haut à droite de l'interface

**Comment by fufeck** [comment]
Je n'arrive pas a reproduire l'erreur. Cependant j'ai remarqué un ralentissement.
Surement en lien avec l'issue https://github.com/BaseAdresseNationale/mes-adresses/issues/735
