### ISSUE TITLE
Ajouter Matomo

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#773]
## Contexte
Il n'existe actuellement aucun suivi sur Mes Adresses actuellement. Mettre en place Matomo permettrait de remonter des statistiques utiles au déploiement.

⚠️ Il est nécessaire de filtrer les URL qui peuvent contenir des informations sensibles.

 https://github.com/BaseAdresseNationale/mes-adresses/pull/777

**Comment by fufeck** [comment]
https://mattermost.incubateur.net/betagouv/pl/dtytnt8ihtdj38raxg3jtyw1er

**Comment by j-saur** [comment]
On peut clore, c'était simplement pour qu'on aborde le sujet des indicateurs que l'on souhaite suivre.
