### ISSUE TITLE
La Vendée manquante sur le dashboard déploiement

### ISSUE THREAD

**Issue by j-saur** [BaseAdresseNationale/mes-adresses#793]
![image](https://github.com/BaseAdresseNationale/mes-adresses/assets/95912586/5c54efc1-7b76-4308-9b63-13ef3f5b34a3)

Les communes vendéenne sont absentes du dashboard alors qu'il existe bien des BAL publiées dans l'api de dépôt.

Exemple avec Aizenay - 85003 :
- Page commune
https://adresse.data.gouv.fr/commune/85003 
- Revisions api dépôt 
https://plateforme.adresse.data.gouv.fr/api-depot/communes/85003/revisions

Il semble donc que les BAL sont bien présentes dans la BAN et qu'il s'agissent simplement d'une question d'affichage sur la carte déploiement.

**Comment by MaGOs92** [comment]
@j-saur problème d'affichage résolu, je ferme l'issue
