### ISSUE TITLE
Migration API Annuaire

### ISSUE THREAD

**Issue by fufeck** [BaseAdresseNationale/mes-adresses#794]
## Context

l'API Annuaire "officielle" intègre désormais tous les changements que l'équipe BAN/BAL avait réalisé sur son fork
Les données sont mises à jour quotidiennement.
il n'est plus nécessaire de maintenir une instance spécifique, reprendre les URL officielles (https://api.gouv.fr/les-api/api_etablissements_publics).
Pour rappel cette API est utilisée sur adresse.data.gouv.fr, sur bal-admin et sur mes-adresses.

**Comment by MaGOs92** [comment]
Hello @fufeck, j'ai pas trouvé l'API annuaire sur bal-admin et mes-adresses.

Sur l'API dépôt, l'API annuaire est appelée lors de la création d'une habilitation pour récupérer l'email de la mairie de la commune et ainsi permettre l'authentification par code PIN.
J'ai testé avec le nouveau end-point, ça fonctionne sans problème
Voici la PR api-depot : https://github.com/BaseAdresseNationale/api-depot/pull/91

Voici la PR adresses.data.gouv.fr : 

@nkokla, tu sais si il y'a d'autres briques qui utilisent le fork de l'API annuaire de bal-1?

Si c'est ok pour vous, je merge et je désactive le CRON RAMovore sur le serveur bal-1

**Comment by antoineludeau** [comment]
Hello, pour moi cette brique est utilisée seulement sur API dépôt et adresse.data.gouv

**Comment by MaGOs92** [comment]
Done!
