### ISSUE TITLE
Changer le format de date mm/dd/yyyy à dd/mm/yyyy

### ISSUE THREAD

**Issue by j-saur** [BaseAdresseNationale/mes-adresses#803]
Sur l'onglet commune, la date de fin d'habilitation apparaît dans un format utilisé dans les pays anglo-saxon plutôt que le standard utilisé en France ou le jour apparaît en premier.

![image](https://github.com/BaseAdresseNationale/mes-adresses/assets/95912586/0591420f-cecb-4d2c-a8ef-c8a8365feec8)

**Comment by MaGOs92** [comment]
Done!
