### ISSUE TITLE
Rajouter une boussole sur la carte

### ISSUE THREAD

**Issue by j-saur** [BaseAdresseNationale/mes-adresses#806]
Suggestions de Manche Numérique : 
 
> Aujourd'hui un cliquer glisser avec le clic droit permet de modifier l'orientation de la carte.
>  Serait-il possible d'ajouter un bouton permettant de revenir à la position initiale (orientée vers le Nord, vue 2D) ? Type "boussole" ou "flèche Nord" ?

Suggestions d'implémentation : 
En haut à droite au niveau des outils de carte, un boussole qui permet : 
- de connaitre le nord
- en cliquant : de remettre le nord en haut (pan) & de remettre l'inclinaison à zéro (tilt)

![image](https://github.com/BaseAdresseNationale/mes-adresses/assets/95912586/02fd3aa1-8137-400a-b62e-2d57c7a7027a)

**Comment by tmerlier** [comment]
Désactiver le changement d'orientation de la carte serait certainement une meilleure option. Cette fonctionnalité n'a pas vraiment d'intérêt dans un contexte. Si l'objectif premier et d'éviter à l'utilisateur de le faire par erreur, alors il vaut mieux prévenir que guérir ;) (ça évitera d'ajouter des boutons supplémentaires et aussi garder une interface la plus sombre possible)
