### ISSUE TITLE
Suppression d'un statut : Prêt à publier

### ISSUE THREAD

**Issue by j-saur** [BaseAdresseNationale/mes-adresses#828]
Problème : 
Le statut prêt à publier apparaît entre le moment ou l'utilisateur clique sur publier et passe l'étape de publication.
Il n'apporte aucune fonctionnalité mise à part celle d'empêcher la suppression de la BAL depuis le menu de Mes Adresses (qui est permise en brouillon).
Cependant, il est source de confusion car il n'appelle à aucune action et au contraire, peut-être interprété comme une mise en attente : 'la BAL est prête'.

Solution : 
Avec pour objectif la simplicité de Mes Adresses et étant donné que le cycle de vie de la BAL Mes Adresses n'est pas claire aujourd'hui pour de nombreux utilisateurs : le statut 'prêt à publier' peut être remplacer par 'brouillon'. 
Si un utilisateur clique sur publier et ne passe pas l'étape d'habilitation, la BAL restera simplement en 'brouillon' sans passé par cette étape intermédiaire de 'prêt à publier'.
Dès lors, le menu en drop down Publication et le bouton 'revenir au brouillon' peuvent être supprimé pour ne garder qu'un simple 'Publier'

![image](https://github.com/BaseAdresseNationale/mes-adresses/assets/95912586/433ea795-e731-4e30-8620-9388fb4bae29)

**Comment by MaGOs92** [comment]
@j-saur Je propose de mettre à jour le statut de la BAL en "ready-to-publish" uniquement quand l'habilitation a été validé et non quand on ouvre le dialog de publication.
Côté mes-adresse-api c'est important de garder le statut "ready-to-publish" pour le première publication d'une BAL.

En plus, dans le cas où l'utilisateur doit forcer la publication de sa BAL, le statut ready-to-publish a du sens
